<?php

include("includes/emailfunctions.php");


session_start();

if($_POST['lastaction'] > $_SESSION['userlastaction']){
 
	
	
	$wasError = false;
	$_SESSION['formdata']=$_POST;
	
	//print_r($_SESSION['formdata']);
	//exit;
	
	// fix slashes
	foreach ($_SESSION['formdata'] as $fkey => $fvalue) {
		$_SESSION['formdata'][$fkey]=stripslashes($fvalue);
	}
	
	
	// check required fields aren't empty
	if ($_SESSION['formdata']['first_name']== "")
	  $wasError=true;
	  
		
	if ($_SESSION['formdata']['last_name']== "")
	  $wasError=true;	
	
	if ($_SESSION['formdata']['company']== "")
	  $wasError=true;
	
	if ($_SESSION['formdata']['job_title']== "")
	  $wasError=true;	       
	
	if ($_SESSION['formdata']['address_line1']== "")
	  $wasError=true;	            
	
	if ($_SESSION['formdata']['postcode']== "")
	  $wasError=true;	
	  
	if ($_SESSION['formdata']['email']== "")
	  $wasError=true;	  
	  
	if ($_SESSION['formdata']['phone']== "")
	  $wasError=true;	  
	
	if ($_SESSION['formdata']['seminar_choice']== "")
	  $wasError=true;	
	
	
	
	//print_r($_SESSION['formdata']);
	
	//print($errStr);
	
	if($wasError) {
		//print("there was an error");
		header("Location: content.php?p=76&retry=1");
		exit;
	}
		
	else {
		
		// feedback form has been submitted and validated, send email and
		// redirect to confirmation page
	
	  define ("SEND_TO_EMAIL", "seminar@boxingorange.com");
	  //define ("SEND_TO_EMAIL", "daniel.eggleston@boxingorange.com");
	  define ("EMAIL_SUBJECT", "2007 Seminar registration from web-site");
	
	  $customername = $_SESSION['formdata']['title'] 
			                . " " . $_SESSION['formdata']['first_name'] 
			                . " " . $_SESSION['formdata']['last_name'] ;
	  $customercompany 	= $_SESSION['formdata']['company'];
	  $customerjobtitle = $_SESSION['formdata']['job_title'];
	  $customeremail 		= $_SESSION['formdata']['email'];
	  $customertelno 		= $_SESSION['formdata']['phone'];
	  $customerseminarchoice = $_SESSION['formdata']['seminar_choice'];
	  
	  $customeroptout = $_SESSION['formdata']['opt_out'];
	
	  $customeraddress = $_SESSION['formdata']['address_line1'] 
	   								 . "\n  " . $_SESSION['formdata']['address_line2']  
	   								 . "\n  " . $_SESSION['formdata']['address_line3']  
	   								 . "\n  " . $_SESSION['formdata']['postcode']  
	   								 . "\n  " . $_SESSION['formdata']['country'] ;
	
	  $colleague1 = $_SESSION['formdata']['colleague1_title'] 
	  						. " " . $_SESSION['formdata']['colleague1_firstname'] 
	  						. " " . $_SESSION['formdata']['colleague1_surname'];
	  						
	  $colleague2 = $_SESSION['formdata']['colleague2_title'] 
	  						. " " . $_SESSION['formdata']['colleague2_firstname']
	  					  . " " . $_SESSION['formdata']['colleague2_surname'];
	  
	  $colleague3 = $_SESSION['formdata']['colleague3_title'] 	
	  						. " " . $_SESSION['formdata']['colleague3_firstname'] 
	  						. " " . $_SESSION['formdata']['colleague3_surname'];
	
	  $message = "";
	
	  $message =  $message .
	              "This message has been generated by the Seminar Registration Form on the\n" .
	              "web-site. Replying to it will contact the customer directly at the\n" .
	              "address they have supplied.\n\n" .
	              "Name: " . $customername . "\n" .
	              "Job Title: " . $customerjobtitle . "\n" .
	              "Company: " . $customercompany . "\n\n" .
	              "E-mail: " . $customeremail . "\n" .
	              "Telephone: " . $customertelno . "\n\n" .
	              "Address:\n  " . $customeraddress . "\n\n" .
	              "Chosen seminar: " . $customerseminarchoice . "\n\n" .
	              
	              "Additional colleagues:\n" .
	              " 1: " . $colleague1 . "\n" .
	              " 2: " . $colleague2 . "\n" .
	              " 3: " . $colleague3 . "\n\n";
	
	  if ($customeroptout == "on") {
	      $message = $message . "CUSTOMER HAS OPTED OUT OF RECEIVING FURTHER INFORMATION FROM US\n";
	  }
	
	  $message = $message . "\nPlease contact the customer as soon as possible to confirm the booking(s).";
	
	  $message .= "\n\nSource IP: " . $_SESSION['formdata']['sourceIP'];
	
	
	  sendEmail($customeremail, SEND_TO_EMAIL, "daniel.eggleston@boxingorange.com", "", EMAIL_SUBJECT, $message);
	
	  //echo $message;
	  //exit;
	  
	  //reset form data
	  $_SESSION['formdata']=array();
	  $_SESSION['seminar_reg_sent']=true;
	  $_SESSION['userlastaction']++; // Increment serial number
	  header("Location: content.php?p=77");
	  exit;
		
	}
}

else {
		// multiple form submission detected
	  header("Location: content.php?p=78");
	  exit;
}
?>
